// ─────────────────────────────────────────────────────────────────────────────
// Masters Pool — Player Config
// Update this file each year before running: node scripts/sync-players.js
// ─────────────────────────────────────────────────────────────────────────────

/** ESPN event ID for this year's Masters. */
const EVENT_ID = "401811941"; // 2026 Masters

/** Pool year. */
const YEAR = 2026;

/**
 * Explicit longshot players for this year's field.
 * These are players who are significant underdogs / lower-ranked field members.
 * Amateurs are always longshots and don't need to be listed here.
 */
const LONGSHOT_PLAYERS = new Set([
  // Mid-tier / borderline pros
  "Gary Woodland",
  "Nick Taylor",
  "Alex Noren",
  "Ryan Fox",
  "Danny Willett",
  "Harris English",
  "Russell Henley",
  "Carlos Ortiz",
  "Davis Riley",
  "J.J. Spaun",
  "Andrew Novak",
  "Max Greyserman",
  "Aaron Rai",
  "Ben Griffin",
  "Tom McKibbin",
  "Kristoffer Reitan",
  "Sam Stevens",
  "Michael Kim",
  "Daniel Berger",
  // Deeper field
  "Haotong Li",
  "Brian Campbell",
  "Maverick McNealy",
  "Jake Knapp",
  "Sami Välimäki",
  "Marco Penge",
  "Harry Hall",
  "Casey Jarvis",
  "Chris Gotterup",
  "Naoyuki Kataoka",
  "Rasmus Neergaard-Petersen",
  "Matt McCarty",
  "Michael Brennan",
  "Jacob Bridgeman",
  "Ryan Gerard",
  "Aldrich Potgieter",
  "Johnny Keefer",
  // Amateurs
  "Brandon Holtz",
  "Mason Howell",
  "Ethan Fang",
  "Fifa Laopakdee",
  "Mateo Pulcini",
  "Jackson Herrington",
]);

/**
 * LIV Golf players in this year's Masters field.
 * Use the exact displayName as it appears in the ESPN API.
 */
const LIV_PLAYERS = new Set([
  "Dustin Johnson",
  "Bryson DeChambeau",
  "Patrick Reed",
  "Sergio García",
  "Charl Schwartzel",
  "Brooks Koepka",
  "Tyrrell Hatton",
  "Carlos Ortiz",
  "Cameron Smith",
  "Jon Rahm",
  "Bubba Watson",
  "Tom McKibbin",
]);

/**
 * Birth years for every player in the field.
 * Used to compute the "Fossil" (40+) tag.
 * Keyed by exact ESPN displayName.
 */
const BIRTH_YEARS = {
  "Ángel Cabrera":             1969,
  "Fred Couples":              1959,
  "Sergio García":             1980,
  "José María Olazábal":       1966,
  "Adam Scott":                1980,
  "Vijay Singh":               1963,
  "Mike Weir":                 1970,
  "Justin Rose":               1980,
  "Zach Johnson":              1976,
  "Bubba Watson":              1978,
  "Charl Schwartzel":          1984,
  "Brian Harman":              1987,
  "Jason Day":                 1987,
  "Dustin Johnson":            1984,
  "Rory McIlroy":              1989,
  "Gary Woodland":             1984,
  "Nick Taylor":               1988,
  "Alex Noren":                1982,
  "Ryan Fox":                  1986,
  "Danny Willett":             1987,
  "Keegan Bradley":            1986,
  "Shane Lowry":               1987,
  "Justin Thomas":             1993,
  "Harris English":            1989,
  "Russell Henley":            1989,
  "Jordan Spieth":             1993,
  "Carlos Ortiz":              1991,
  "Tommy Fleetwood":           1991,
  "Tyrrell Hatton":            1991,
  "Patrick Reed":              1990,
  "Hideki Matsuyama":          1992,
  "Patrick Cantlay":           1992,
  "Brooks Koepka":             1990,
  "Si Woo Kim":                1995,
  "Sepp Straka":               1993,
  "Max Homa":                  1990,
  "Michael Kim":               1993,
  "Daniel Berger":             1993,
  "Matt Fitzpatrick":          1994,
  "Corey Conners":             1991,
  "Cameron Smith":             1993,
  "Haotong Li":                1995,
  "Scottie Scheffler":         1996,
  "Brian Campbell":            1984,
  "Maverick McNealy":          1994,
  "Jon Rahm":                  1994,
  "Jake Knapp":                1994,
  "Sam Burns":                 1996,
  "Bryson DeChambeau":         1993,
  "Davis Riley":               1995,
  "Xander Schauffele":         1993,
  "J.J. Spaun":                1989,
  "Kurt Kitayama":             1995,
  "Collin Morikawa":           1997,
  "Aaron Rai":                 1994,
  "Max Greyserman":            1998,
  "Wyndham Clark":             1993,
  "Nicolai Højgaard":          2001,
  "Rasmus Højgaard":           2000,
  "Andrew Novak":              1993,
  "Robert MacIntyre":          1996,
  "Sungjae Im":                1998,
  "Brandon Holtz":             2003,
  "Tom McKibbin":              2002,
  "Kristoffer Reitan":         2002,
  "Viktor Hovland":            1997,
  "Ludvig Åberg":              2000,
  "Ben Griffin":               1994,
  "Nico Echavarria":           1991,
  "Min Woo Lee":               1998,
  "Akshay Bhatia":             2004,
  "Cameron Young":             1997,
  "Sam Stevens":               1997,
  "Sami Välimäki":             1999,
  "Marco Penge":               1998,
  "Harry Hall":                1996,
  "Casey Jarvis":              2003,
  "Chris Gotterup":            1999,
  "Naoyuki Kataoka":           1984,
  "Rasmus Neergaard-Petersen": 2001,
  "Matt McCarty":              1997,
  "Michael Brennan":           1997,
  "Jacob Bridgeman":           2000,
  "Ryan Gerard":               1998,
  "Aldrich Potgieter":         2003,
  "Johnny Keefer":             1997,
  "Mason Howell":              2003,
  "Ethan Fang":                2005,
  "Fifa Laopakdee":            2004,
  "Mateo Pulcini":             2003,
  "Jackson Herrington":        2003,
};

/**
 * Players that the ESPN leaderboard API omits from its competitor list.
 * These are inserted directly rather than coming from the ESPN sync.
 * country must match the ESPN flag.description format.
 */
const MANUAL_PLAYERS = [
  { name: "Fred Couples",     country: "United States" },
  { name: "Matt Fitzpatrick", country: "England"       },
  { name: "Corey Conners",    country: "Canada"        },
  { name: "Cameron Smith",    country: "Australia"     },
  { name: "Haotong Li",       country: "China"         },
  { name: "Brian Campbell",   country: "United States" },
  { name: "Maverick McNealy", country: "United States" },
  { name: "Jon Rahm",         country: "Spain"         },
  { name: "Jake Knapp",       country: "United States" },
  { name: "Sam Burns",        country: "United States" },
  { name: "Scottie Scheffler",country: "United States" },
];

/**
 * Authoritative OWGR rankings for the 2026 Masters field.
 * Used as a fallback when Sportradar doesn't cover a player (outside top 200, LIV, etc.).
 * null = no world ranking (amateurs, honorary invitees).
 * Keyed by ESPN displayName.
 */
const MANUAL_RANKINGS = {
  "Ludvig Åberg":               17,
  "Daniel Berger":              38,
  "Akshay Bhatia":              21,
  "Keegan Bradley":             26,
  "Michael Brennan":            47,
  "Jacob Bridgeman":            18,
  "Sam Burns":                  33,
  "Ángel Cabrera":              null,
  "Brian Campbell":             112,
  "Patrick Cantlay":            35,
  "Wyndham Clark":              78,
  "Corey Conners":              44,
  "Fred Couples":               null,
  "Jason Day":                  41,
  "Bryson DeChambeau":          24,
  "Nico Echavarria":            40,
  "Harris English":             20,
  "Ethan Fang":                 null,
  "Matt Fitzpatrick":           6,
  "Tommy Fleetwood":            4,
  "Ryan Fox":                   51,
  "Sergio García":              345,
  "Ryan Gerard":                29,
  "Chris Gotterup":             11,
  "Max Greyserman":             59,
  "Ben Griffin":                16,
  "Harry Hall":                 62,
  "Brian Harman":               50,
  "Tyrrell Hatton":             31,
  "Russell Henley":             12,
  "Jackson Herrington":         null,
  "Nicolai Højgaard":           36,
  "Rasmus Højgaard":            57,
  "Brandon Holtz":              null,
  "Max Homa":                   163,
  "Viktor Hovland":             22,
  "Mason Howell":               null,
  "Sungjae Im":                 71,
  "Casey Jarvis":               70,
  "Dustin Johnson":             593,
  "Zach Johnson":               321,
  "Naoyuki Kataoka":            372,
  "Johnny Keefer":              64,
  "Michael Kim":                43,
  "Si Woo Kim":                 28,
  "Kurt Kitayama":              34,
  "Jake Knapp":                 42,
  "Brooks Koepka":              169,
  "Fifa Laopakdee":             null,
  "Min Woo Lee":                25,
  "Haotong Li":                 84,
  "Shane Lowry":                32,
  "Robert MacIntyre":           8,
  "Hideki Matsuyama":           14,
  "Matt McCarty":               49,
  "Rory McIlroy":               2,
  "Tom McKibbin":               105,
  "Maverick McNealy":           27,
  "Collin Morikawa":            7,
  "Rasmus Neergaard-Petersen":  69,
  "Alex Noren":                 19,
  "Andrew Novak":               48,
  "José María Olazábal":        null,
  "Carlos Ortiz":               161,
  "Marco Penge":                37,
  "Aldrich Potgieter":          77,
  "Mateo Pulcini":              null,
  "Jon Rahm":                   30,
  "Aaron Rai":                  39,
  "Patrick Reed":               23,
  "Kristoffer Reitan":          46,
  "Davis Riley":                120,
  "Justin Rose":                9,
  "Xander Schauffele":          10,
  "Scottie Scheffler":          1,
  "Charl Schwartzel":           566,
  "Adam Scott":                 53,
  "Vijay Singh":                null,
  "Cameron Smith":              222,
  "J.J. Spaun":                 5,
  "Jordan Spieth":              61,
  "Sam Stevens":                45,
  "Sepp Straka":                13,
  "Nick Taylor":                67,
  "Justin Thomas":              15,
  "Sami Välimäki":              56,
  "Bubba Watson":               702,
  "Mike Weir":                  null,
  "Danny Willett":              400,
  "Gary Woodland":              52,
  "Cameron Young":              3,
};

/**
 * Outright winner odds (American format) for the 2026 Masters field.
 * Keyed by ESPN displayName. Update each year before running sync.
 */
const ODDS = {
  "Scottie Scheffler":          490,
  "Jon Rahm":                   910,
  "Bryson DeChambeau":          1075,
  "Rory McIlroy":               1175,
  "Ludvig Åberg":               1700,
  "Xander Schauffele":          1800,
  "Cameron Young":              2300,
  "Tommy Fleetwood":            2300,
  "Matt Fitzpatrick":           2350,
  "Hideki Matsuyama":           2700,
  "Collin Morikawa":            3100,
  "Robert MacIntyre":           3400,
  "Min Woo Lee":                3500,
  "Justin Rose":                3500,
  "Brooks Koepka":              3700,
  "Chris Gotterup":             4200,
  "Jordan Spieth":              4200,
  "Patrick Reed":               4300,
  "Viktor Hovland":             4500,
  "Russell Henley":             4700,
  "Si Woo Kim":                 4900,
  "Justin Thomas":              5400,
  "Akshay Bhatia":              5700,
  "Patrick Cantlay":            5800,
  "Adam Scott":                 6000,
  "Jason Day":                  6700,
  "Jake Knapp":                 6700,
  "Shane Lowry":                6800,
  "Sam Burns":                  7000,
  "J.J. Spaun":                 7200,
  "Sepp Straka":                7400,
  "Tyrrell Hatton":             7600,
  "Nicolai Højgaard":           7800,
  "Corey Conners":              7800,
  "Maverick McNealy":           8400,
  "Jacob Bridgeman":            8600,
  "Kurt Kitayama":              9800,
  "Harris English":             10000,
  "Gary Woodland":              10500,
  "Daniel Berger":              10500,
  "Ben Griffin":                11000,
  "Cameron Smith":              11000,
  "Sungjae Im":                 11500,
  "Max Homa":                   12000,
  "Rasmus Højgaard":            12500,
  "Keegan Bradley":             13500,
  "Marco Penge":                14000,
  "Harry Hall":                 15500,
  "Ryan Gerard":                16000,
  "Alex Noren":                 16000,
  "Sam Stevens":                18000,
  "Nick Taylor":                19500,
  "Ryan Fox":                   21000,
  "Wyndham Clark":              21000,
  "Michael Kim":                22500,
  "Max Greyserman":             22500,
  "Brian Harman":               22500,
  "Aaron Rai":                  23000,
  "Kristoffer Reitan":          23000,
  "Sergio García":              24000,
  "Casey Jarvis":               24000,
  "Carlos Ortiz":               25000,
  "Dustin Johnson":             26000,
  "Tom McKibbin":               26000,
  "Haotong Li":                 30000,
  "Matt McCarty":               30000,
  "Andrew Novak":               31000,
  "Nico Echavarria":            34000,
  "Rasmus Neergaard-Petersen":  34000,
  "Sami Välimäki":              39000,
  "Aldrich Potgieter":          39000,
  "Michael Brennan":            40000,
  "Johnny Keefer":              40000,
  "Bubba Watson":               55000,
  "Zach Johnson":               55000,
  "Charl Schwartzel":           65000,
  "Davis Riley":                85000,
  "Mason Howell":               200000,
  "Brian Campbell":             250000,
  "Danny Willett":              250000,
  "Ángel Cabrera":              325000,
  "Ethan Fang":                 350000,
  "Fifa Laopakdee":             350000,
  "Naoyuki Kataoka":            450000,
  "Brandon Holtz":              500000,
  "Vijay Singh":                500000,
  "Mike Weir":                  500000,
  "Fred Couples":               500000,
  "José María Olazábal":        500000,
  "Mateo Pulcini":              500000,
  "Jackson Herrington":         500000,
};

module.exports = { EVENT_ID, YEAR, LONGSHOT_PLAYERS, LIV_PLAYERS, BIRTH_YEARS, MANUAL_PLAYERS, MANUAL_RANKINGS, ODDS };
